const path = require('path');

const DATA_DIR = path.resolve(__dirname, '..', 'support', 'data', 'input-dir');

const {
    autogenerateDeckFromDir,
    pathToTitle,
    knownCodeFileExtensions,
    isCodeFile,
} = require('../../lib/utils');

describe('utils module', () => {
    describe('has a pathToTitle function that', () => {
        it('exists', () => {
            expect(pathToTitle).toBeTruthy();
        });

        it('converts simple paths to a title', () => {
            expect(pathToTitle('this/is/some/path'))
                .toEqual('this - is - some - path');
            expect(pathToTitle('05-Demo/Start'))
                .toEqual('Demo - Start');
        });

        it('splits camel case', () => {
            expect(pathToTitle('5-DemoStart'))
                .toEqual('Demo Start');
            expect(pathToTitle('5-DemoStart/Another_CamelCase____Thing'))
                .toEqual('Demo Start - Another Camel Case Thing');
        });
    });

    describe('has a list of known code files that', () => {
        it('exists', () => {
            expect(knownCodeFileExtensions).toBeTruthy();
            expect(knownCodeFileExtensions.length > 10).toBeTruthy();
        });

        it('contains some well known ones', () => {
            expect(knownCodeFileExtensions.includes('js')).toBeTruthy();
            expect(knownCodeFileExtensions.includes('html')).toBeTruthy();
            expect(knownCodeFileExtensions.includes('py')).toBeTruthy();
            expect(knownCodeFileExtensions.includes('^dockerfile')).toBeTruthy();
        });
    });

    describe('has a function for guessing if a file is a code file that', () => {
        it('exists', () => {
            expect(isCodeFile).toBeTruthy();
        });

        it('checks a few common file types', () => {
            expect(isCodeFile('my/file/path.md')).toBeTruthy();
            expect(isCodeFile('my/file/path.JS')).toBeTruthy();
        });

        it('checks extensionless files', () => {
            expect(isCodeFile('asdfaasd')).not.toBeTruthy();
            expect(isCodeFile('Dockerfile')).toBeTruthy();
            expect(isCodeFile('some/path/to/makefile')).toBeTruthy();
        });
    });

    describe('has a function for generating decks from a dir that', () => {
        it('exists', () => {
            expect(autogenerateDeckFromDir).toBeTruthy();
        });

        it('generates an expected deck from a simple input dir', () => {
            const deckList = autogenerateDeckFromDir(`${DATA_DIR}/simple/`);
            expect(deckList.length).toEqual(1);
            const slide = deckList[0];
            expect(slide.editor).toContain('02-AnotherExample.html');
            expect(slide.editor).toContain('test.html');
            expect(slide.browser).toBeTruthy();
            expect(slide.browser).toContain('.html');
            expect(slide.browser).toContain('file:///');
            expect(slide.terminal).not.toBeTruthy();
            expect(slide.title).toEqual('simple');
        });

        it('generates an expected deck from a complex input dir', () => {
            const deckList = autogenerateDeckFromDir(`${DATA_DIR}/complex/`);
            expect(deckList.length).toEqual(5);
            let slide = deckList[0];
            expect(slide.title).toEqual('First');
            expect(slide.editor).toContain('outer.js');
            expect(slide.browser).not.toBeTruthy();
            expect(slide.terminal).toContain('01-First');
            expect(slide.markdown).toBeTruthy();
            expect(slide.markdown).toContain('i am markdown');
            slide = deckList[1];
            expect(slide.title).toEqual('Second Thing');
            expect(slide.editor).toContain('outer-second.js');
            expect(slide.browser).not.toBeTruthy();
            expect(slide.terminal).toContain('02-SecondThing');
            slide = deckList[2];
            expect(slide.title).toEqual('Third thing');
            expect(slide.editor).toContain('outer.js');
            expect(slide.browser).not.toBeTruthy();
            expect(slide.terminal).toContain('03-Third_thing');
            slide = deckList[3];
            expect(slide.title).toEqual('Third thing - Demo');
            expect(slide.editor).toContain('test-solved.html');
            expect(slide.browser).toBeTruthy();
            slide = deckList[4];
            expect(slide.title).toEqual('Third thing - Example');
            expect(slide.editor).toContain('test-unsolved.html');
            expect(slide.browser).toBeTruthy();
        });
    });
});
